aaryan_fiver:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: vinita-388203
      dataset: dev
      threads: 4  
      OPTIONAL_CONFIG: VALUE

    prod:
      type: bigquery
      method: oauth
      project: vinita-388203
      dataset: vinita-388203
      threads: 4  
      OPTIONAL_CONFIG: VALUE

  target: dev